# feeder
feeder: feeders.feeder_uav.Feeder

data_path: /root/autodl-fs/UAV-SAR/data/uav/MMVRAC_CSv1_train_angle.npz
window_size: 64
random_rot: False
use_vel: False
use_angle: True

# model
num_class: 155
num_point: 17
num_person: 2
graph: graph.uav.Graph
k: 1
in_channels: 9
cl_mode: 'ST-Multi-Level'

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [90, 100]
warm_up_epoch: 5

# training
device: 0
batch_size: 128
test_batch_size: 128
num_epoch: 150
nesterov: True

half: True