work_dir: ./work_dir/uav/test_joint

# feeder
feeder: feeders.feeder_uav.Feeder

test_feeder_args:
  data_path: ./data/uav/v1/test_joint_B.npy
  label_path: ./data/uav/v1/test_label_B.pkl
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False
  normalization: True

# model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav_human.Graph
  graph_args:
    labeling_mode: 'spatial'

