work_dir: ./work_dir/test_bone

# feeder
feeder: feeders.feeder_uav.Feeder

test_feeder_args:
  data_path: ../data/test_joint.npy
  label_path: ../data/test_label.pkl
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False
  normalization: True

# model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav_human.Graph
  graph_args:
    labeling_mode: 'spatial'

