# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/test_joint.npy
  label_path: ./data/test_label.pkl
  debug: False
  window_size: -1
  p_interval: [ 0.95 ]
  bone: False
  vel: False
  frame: False

# model
model: model.vegcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0]
test_batch_size: 256
weights: ./weights/cdgcn_joint/cdgcn_joint-34-18270.pt

save_score: True
